#!/usr/bin/env bash
# Provision a local Windows VM ("attached VM") that runs Noitom Axis Studio.
#
# The VM owns the Perception Neuron USB/RNDIS transceiver exclusively (see
# attach-usb.sh); Axis Studio streams BVH/Calc frames over unicast UDP/TCP to
# this Linux host, where MocapApi / Mocap Studio / the gr00t bridge consume
# them. Architecture reference: studio/docs/USB_ON_LINUX.md, "Architecture B".
#
# Tested target: Ubuntu 22.04/24.04 x86_64 with KVM. Requires VT-x/AMD-V
# enabled in firmware. Cloud instances without nested virtualization
# (no /dev/kvm) cannot run the VM; use --dry-run there to inspect commands.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VM_NAME="axis-studio"
WINDOWS_ISO=""
WINDOWS_ISO_URL=""
WINDOWS_VERSION="win11"          # win10 | win11
MEMORY_MIB=8192
VCPUS=4
DISK_SIZE_GIB=120
IMAGES_DIR="/var/lib/libvirt/images"
VIRTIO_WIN_URL="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso"
AXIS_INSTALLER=""
AXIS_INSTALLER_URL=""
AXIS_INSTALLER_KIND=""
DOWNLOAD_AXIS_STUDIO_3=0
AXIS_MEDIA=1
AXIS_GUEST_ASSETS_DIR="${SCRIPT_DIR}/windows"
AXIS_MEDIA_STAGING=""
AXIS_SETUP_ISO=""
AXIS_SETUP_ISO_TEMP=""
AXIS_SETUP_ISO_CREATED=0
DOWNLOAD_TEMP_PATH=""
WINDOWS_VM_ISO=""
WINDOWS_VM_ISO_TEMP=""
STAGED_WINDOWS_ISO_CREATED=0
VIRTIO_ISO=""
VIRTIO_ISO_TEMP=""
DISK_PATH=""
DISK_PATH_TEMP=""
DISK_CREATED=0
DOWNLOAD_ONLY=0
DRY_RUN=0
SKIP_PACKAGES=0
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/axis-vm"
MEDIA_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/axis-vm/downloads"
WINDOWS_11_DOWNLOAD_PAGE="https://www.microsoft.com/software-download/windows11"
WINDOWS_10_DOWNLOAD_PAGE="https://www.microsoft.com/software-download/windows10ISO"
WINDOWS_DOWNLOAD_PAGE="${WINDOWS_11_DOWNLOAD_PAGE}"
NOITOM_DOWNLOAD_PAGE="https://shop.noitom.com.cn/common/product_item/index.jhtml?productItemId=3"
NOITOM_ACCOUNT_PAGE="https://account.noitom.com/"
DEFAULT_AXIS_STUDIO_3_URL="https://cdn.noitom.com/download/Axis%20Studio%203%20%28Anti-Mag%29/Axis_Studio_nacs_x64_3_0_14004_2620_20251222173616363.msi"

usage() {
    cat <<EOF
Usage: $(basename "$0") (--windows-iso PATH | --windows-iso-url URL) [options]

Creates the Axis Studio Windows VM used by the mocap station.

Required (choose one):
  --windows-iso PATH     Existing Windows 10/11 installer ISO
  --windows-iso-url URL  Fresh direct HTTPS ISO URL generated by Microsoft

Options:
  --name NAME            Libvirt domain name (default: ${VM_NAME})
  --windows-version VER  win10 or win11 (default: ${WINDOWS_VERSION})
  --memory MIB           Guest RAM in MiB (default: ${MEMORY_MIB})
  --vcpus N              Guest vCPUs (default: ${VCPUS})
  --disk-size GIB        Guest disk size in GiB, sparse (default: ${DISK_SIZE_GIB})
  --images-dir DIR       Where disk/ISOs live (default: ${IMAGES_DIR})
  --axis-installer PATH  Put an existing Axis Studio .exe/.msi/.zip on the guest
                         setup CD; without it, the CD opens Noitom's download page
  --axis-installer-url URL
                         Download an Axis Studio .exe/.msi/.zip to the media cache
  --download-axis-studio-3
                         Download the pinned Axis Studio 3 Anti-Mag MSI from Noitom
                         (only for compatible anti-magnetic hardware)
  --media-cache DIR      Download cache (default: ${MEDIA_CACHE_DIR})
  --download-only        Download/validate URL media, then exit before VM setup
  --skip-axis-media      Do not create or attach the guided AXIS_SETUP CD
  --skip-packages        Do not apt-get install host packages
  --dry-run              Print the commands without executing them
  -h, --help             Show this help

After Windows setup, open the AXIS_SETUP CD in the guest and run
START-AXIS-SETUP.cmd. It installs the supplied Axis Studio package (if any)
and walks the user through account/Product-ID activation and login without
collecting credentials. Continue with vm/README.md for USB passthrough and BVH.

Official downloads:
  Windows ${WINDOWS_VERSION#win} ISO: ${WINDOWS_DOWNLOAD_PAGE}
  Axis Studio:    ${NOITOM_DOWNLOAD_PAGE}
  Axis account:   ${NOITOM_ACCOUNT_PAGE}

Microsoft's generated ISO links expire after 24 hours. Download the ISO in a
browser and pass its actual path, or paste the fresh direct link with
--windows-iso-url. Licensed installers are downloaded from their publishers
and are never stored in this repository.
EOF
}

log()  { printf '\033[1;34m[axis-vm]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[axis-vm]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[axis-vm]\033[0m %s\n' "$*" >&2; exit 1; }

run() {
    if [ "${DRY_RUN}" -eq 1 ]; then
        printf '\033[2m[dry-run]\033[0m %s\n' "$*"
    else
        "$@"
    fi
}

cleanup() {
    local exit_status=$?
    local domain_names=""
    local domain_state="unknown"
    local privileged_temp=""
    if [ -n "${AXIS_MEDIA_STAGING}" ] && [ -d "${AXIS_MEDIA_STAGING}" ]; then
        rm -rf -- "${AXIS_MEDIA_STAGING}"
    fi
    if [ -n "${DOWNLOAD_TEMP_PATH}" ] && [ -f "${DOWNLOAD_TEMP_PATH}" ]; then
        rm -f -- "${DOWNLOAD_TEMP_PATH}"
    fi
    for privileged_temp in \
        "${AXIS_SETUP_ISO_TEMP}" \
        "${WINDOWS_VM_ISO_TEMP}" \
        "${VIRTIO_ISO_TEMP}" \
        "${DISK_PATH_TEMP}"; do
        if [ -n "${privileged_temp}" ]; then
            sudo -n rm -f -- "${privileged_temp}" 2>/dev/null \
                || warn "could not remove temporary setup artifact: ${privileged_temp}"
        fi
    done
    if [ "${exit_status}" -ne 0 ] \
        && { [ "${STAGED_WINDOWS_ISO_CREATED}" -eq 1 ] \
            || [ "${AXIS_SETUP_ISO_CREATED}" -eq 1 ] \
            || [ "${DISK_CREATED}" -eq 1 ]; }; then
        if command -v virsh >/dev/null 2>&1 \
            && domain_names="$(sudo -n virsh list --all --name 2>/dev/null)"; then
            if printf '%s\n' "${domain_names}" | grep -Fxq -- "${VM_NAME}"; then
                domain_state="present"
            else
                domain_state="absent"
            fi
        fi
        if [ "${domain_state}" = "present" ]; then
            warn "preserving VM artifacts because domain '${VM_NAME}' was defined"
        elif [ "${domain_state}" = "unknown" ]; then
            warn "preserving VM artifacts because domain absence could not be verified"
        else
            if [ "${STAGED_WINDOWS_ISO_CREATED}" -eq 1 ]; then
                sudo -n rm -f -- "${WINDOWS_VM_ISO}" 2>/dev/null \
                    && warn "removed staged Windows ISO after failed setup: ${WINDOWS_VM_ISO}" \
                    || warn "could not remove staged Windows ISO after failed setup: ${WINDOWS_VM_ISO}"
            fi
            if [ "${AXIS_SETUP_ISO_CREATED}" -eq 1 ]; then
                sudo -n rm -f -- "${AXIS_SETUP_ISO}" 2>/dev/null \
                    && warn "removed Axis setup ISO after failed setup: ${AXIS_SETUP_ISO}" \
                    || warn "could not remove Axis setup ISO after failed setup: ${AXIS_SETUP_ISO}"
            fi
            if [ "${DISK_CREATED}" -eq 1 ]; then
                sudo -n rm -f -- "${DISK_PATH}" 2>/dev/null \
                    && warn "removed guest disk after failed setup: ${DISK_PATH}" \
                    || warn "could not remove guest disk after failed setup: ${DISK_PATH}"
            fi
        fi
    fi
    return "${exit_status}"
}
trap cleanup EXIT

cleanup_axis_media_staging() {
    if [ -n "${AXIS_MEDIA_STAGING}" ] && [ -d "${AXIS_MEDIA_STAGING}" ]; then
        rm -rf -- "${AXIS_MEDIA_STAGING}"
    fi
}

require_https_url() {
    local option_name="$1"
    local url="$2"
    case "${url}" in
        https://?*) ;;
        *) die "${option_name} accepts only a direct HTTPS URL" ;;
    esac
}

require_microsoft_iso_url() {
    local authority="${1#https://}"
    local port=""
    local host="${authority%%/*}"
    case "${host}" in
        *"@"*|*"\\"*)
            die "--windows-iso-url must not contain URL credentials or backslashes"
            ;;
    esac
    if [[ "${host}" == *:* ]]; then
        port="${host#*:}"
        host="${host%%:*}"
        [[ "${port}" =~ ^[0-9]+$ ]] \
            || die "--windows-iso-url contains an invalid port"
    fi
    host="${host,,}"
    [[ "${host}" =~ ^[a-z0-9.-]+$ ]] \
        || die "--windows-iso-url contains an invalid host"
    case "${host}" in
        microsoft.com|*.microsoft.com) ;;
        *) die "--windows-iso-url must be a direct microsoft.com URL; download organization mirrors separately and pass them with --windows-iso" ;;
    esac
}

media_url_cache_key() {
    local identity="$1"
    local query_policy="${2:-include}"
    if [ "${query_policy}" = "strip" ]; then
        identity="${identity%%\?*}"
    fi
    identity="${identity%%\#*}"
    command -v sha256sum >/dev/null || \
        die "sha256sum is required to identify cached publisher downloads"
    printf '%s' "${identity}" | sha256sum | awk '{ print substr($1, 1, 16) }'
}

axis_installer_extension() {
    local url_path="${1%%\?*}"
    url_path="${url_path%%\#*}"
    case "${url_path}" in
        *.[eE][xX][eE]) printf '%s\n' exe ;;
        *.[mM][sS][iI]) printf '%s\n' msi ;;
        *.[zZ][iI][pP]) printf '%s\n' zip ;;
        *) die "--axis-installer-url must end in .exe, .msi, or .zip (before any query string)" ;;
    esac
}

validate_downloaded_media() {
    local path="$1"
    local kind="$2"
    local signature=""
    case "${kind}" in
        iso)
            signature="$(LC_ALL=C dd if="${path}" bs=1 skip=32769 count=5 2>/dev/null || true)"
            [ "${signature}" = "CD001" ]
            ;;
        msi)
            signature="$(od -An -tx1 -N8 "${path}" 2>/dev/null | tr -d ' \n')"
            [ "${signature}" = "d0cf11e0a1b11ae1" ]
            ;;
        exe)
            signature="$(od -An -tx1 -N2 "${path}" 2>/dev/null | tr -d ' \n')"
            [ "${signature}" = "4d5a" ]
            ;;
        zip)
            signature="$(od -An -tx1 -N2 "${path}" 2>/dev/null | tr -d ' \n')"
            [ "${signature}" = "504b" ]
            ;;
        *) return 1 ;;
    esac
}

validate_privileged_iso() {
    local path="$1"
    local signature=""
    signature="$(sudo dd if="${path}" bs=1 skip=32769 count=5 2>/dev/null || true)"
    [ "${signature}" = "CD001" ]
}

ensure_virtio_iso() {
    if [ "${DRY_RUN}" -eq 1 ]; then
        VIRTIO_ISO_TEMP="${VIRTIO_ISO}.incoming.$$"
        run sudo mkdir -p "${IMAGES_DIR}"
        run sudo curl -fL --retry 3 --proto '=https' --proto-redir '=https' \
            --tlsv1.2 -o "${VIRTIO_ISO_TEMP}" "${VIRTIO_WIN_URL}"
        printf '\033[2m[dry-run]\033[0m validate ISO-9660 signature and publish %s atomically\n' \
            "${VIRTIO_ISO}"
        VIRTIO_ISO_TEMP=""
        return
    fi

    sudo mkdir -p "${IMAGES_DIR}"
    if sudo test -L "${VIRTIO_ISO}"; then
        die "virtio-win cache path must not be a symlink: ${VIRTIO_ISO}"
    fi
    if sudo test -e "${VIRTIO_ISO}" && ! sudo test -f "${VIRTIO_ISO}"; then
        die "virtio-win cache path is not a regular file: ${VIRTIO_ISO}"
    fi
    if sudo test -f "${VIRTIO_ISO}" && validate_privileged_iso "${VIRTIO_ISO}"; then
        log "Using cached virtio-win driver ISO: ${VIRTIO_ISO}"
        return
    fi
    if sudo test -e "${VIRTIO_ISO}"; then
        warn "cached virtio-win ISO is invalid; replacing it after a verified download"
    else
        log "Downloading virtio-win driver ISO (Windows storage/network drivers)"
    fi

    VIRTIO_ISO_TEMP="$(sudo mktemp "${IMAGES_DIR}/.virtio-win.iso.incoming.XXXXXX")"
    if ! sudo curl -fL --retry 3 --proto '=https' --proto-redir '=https' \
        --tlsv1.2 -o "${VIRTIO_ISO_TEMP}" "${VIRTIO_WIN_URL}"; then
        die "could not download the virtio-win driver ISO from ${VIRTIO_WIN_URL}"
    fi
    validate_privileged_iso "${VIRTIO_ISO_TEMP}" \
        || die "downloaded virtio-win file is not a valid ISO; the existing cache was left unchanged"
    sudo chmod 0644 "${VIRTIO_ISO_TEMP}"
    sudo mv -T -- "${VIRTIO_ISO_TEMP}" "${VIRTIO_ISO}"
    VIRTIO_ISO_TEMP=""
}

download_media() {
    local label="$1"
    local url="$2"
    local destination="$3"
    local kind="$4"
    local fallback_page="$5"

    if [ "${DRY_RUN}" -eq 1 ]; then
        printf '\033[2m[dry-run]\033[0m download %s from its publisher to %s\n' \
            "${label}" "${destination}"
        return
    fi
    if [ -e "${destination}" ] || [ -L "${destination}" ]; then
        [ -f "${destination}" ] && [ ! -L "${destination}" ] \
            || die "media cache path is not a regular file: ${destination}"
        validate_downloaded_media "${destination}" "${kind}" \
            || die "cached ${label} is not a valid ${kind} file: ${destination}"
        log "Using cached ${label}: ${destination}"
        return
    fi

    command -v curl >/dev/null || \
        die "curl is required to download ${label}; install curl or pass a local file"
    mkdir -p -- "${MEDIA_CACHE_DIR}"
    DOWNLOAD_TEMP_PATH="$(mktemp "${MEDIA_CACHE_DIR}/.${kind}.part.XXXXXX")"
    log "Downloading ${label} to ${destination}"
    if ! curl -fL --retry 3 --proto '=https' --proto-redir '=https' --tlsv1.2 \
        -o "${DOWNLOAD_TEMP_PATH}" "${url}"; then
        die "could not download ${label}; the link may have expired or require browser/account access. Use ${fallback_page} and pass the downloaded local file"
    fi
    validate_downloaded_media "${DOWNLOAD_TEMP_PATH}" "${kind}" \
        || die "downloaded ${label} is not a valid ${kind} file; use the direct download link, not an HTML page"
    chmod 0644 "${DOWNLOAD_TEMP_PATH}"
    if ! ln -- "${DOWNLOAD_TEMP_PATH}" "${destination}"; then
        die "another process created the media cache file while downloading: ${destination}"
    fi
    rm -f -- "${DOWNLOAD_TEMP_PATH}"
    DOWNLOAD_TEMP_PATH=""
}

download_requested_media() {
    if [ -n "${WINDOWS_ISO_URL}" ]; then
        download_media \
            "Windows ${WINDOWS_VERSION} x86-64 ISO" \
            "${WINDOWS_ISO_URL}" "${WINDOWS_ISO}" iso "${WINDOWS_DOWNLOAD_PAGE}"
    fi
    if [ -n "${AXIS_INSTALLER_URL}" ]; then
        download_media \
            "Axis Studio installer" \
            "${AXIS_INSTALLER_URL}" "${AXIS_INSTALLER}" \
            "${AXIS_INSTALLER_KIND}" "${NOITOM_DOWNLOAD_PAGE}"
    fi
}

build_axis_setup_media() {
    local installer_name=""
    local media_payload=""

    if [ "${DRY_RUN}" -eq 1 ]; then
        printf '\033[2m[dry-run]\033[0m build guided Axis Studio setup CD at %s' "${AXIS_SETUP_ISO}"
        if [ -n "${AXIS_INSTALLER}" ]; then
            printf ' with installer %s' "${AXIS_INSTALLER}"
        fi
        printf '\n'
        return
    fi

    command -v xorriso >/dev/null || \
        die "xorriso not found (install it, or rerun without --skip-packages)"
    [ -r "${AXIS_GUEST_ASSETS_DIR}/START-AXIS-SETUP.cmd" ] || \
        die "Guest setup assets missing from ${AXIS_GUEST_ASSETS_DIR}"
    [ -r "${AXIS_GUEST_ASSETS_DIR}/README.txt" ] || \
        die "Guest setup assets missing from ${AXIS_GUEST_ASSETS_DIR}"

    AXIS_MEDIA_STAGING="$(mktemp -d -t axis-vm-media.XXXXXX)"
    media_payload="${AXIS_MEDIA_STAGING}/payload"
    mkdir "${media_payload}"
    cp -- "${AXIS_GUEST_ASSETS_DIR}/START-AXIS-SETUP.cmd" "${media_payload}/"
    cp -- "${AXIS_GUEST_ASSETS_DIR}/README.txt" "${media_payload}/"
    if [ -n "${AXIS_INSTALLER}" ]; then
        case "${AXIS_INSTALLER}" in
            *.[eE][xX][eE]) installer_name="AxisStudioSetup.exe" ;;
            *.[mM][sS][iI]) installer_name="AxisStudioSetup.msi" ;;
            *.[zZ][iI][pP]) installer_name="AxisStudioSetup.zip" ;;
        esac
        cp -- "${AXIS_INSTALLER}" "${media_payload}/${installer_name}"
    fi

    log "Creating guided Axis Studio setup CD"
    xorriso -as mkisofs -quiet -iso-level 3 -J -joliet-long -R \
        -V AXIS_SETUP -o "${AXIS_MEDIA_STAGING}/axis-setup.iso" "${media_payload}"
    sudo mkdir -p "${IMAGES_DIR}"
    AXIS_SETUP_ISO_TEMP="$(sudo mktemp "${IMAGES_DIR}/.${VM_NAME}-axis-setup.iso.incoming.XXXXXX")"
    sudo install -m 0644 "${AXIS_MEDIA_STAGING}/axis-setup.iso" "${AXIS_SETUP_ISO_TEMP}"
    if ! sudo ln -- "${AXIS_SETUP_ISO_TEMP}" "${AXIS_SETUP_ISO}"; then
        die "Axis setup ISO appeared while provisioning: ${AXIS_SETUP_ISO}"
    fi
    AXIS_SETUP_ISO_CREATED=1
    sudo rm -f -- "${AXIS_SETUP_ISO_TEMP}"
    AXIS_SETUP_ISO_TEMP=""
    cleanup_axis_media_staging
    AXIS_MEDIA_STAGING=""
}

require_option_value() {
    [ "$#" -ge 2 ] && [ -n "$2" ] || die "$1 requires a value"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --windows-iso)      require_option_value "$@"; WINDOWS_ISO="$2"; shift 2 ;;
        --windows-iso-url)  require_option_value "$@"; WINDOWS_ISO_URL="$2"; shift 2 ;;
        --name)             require_option_value "$@"; VM_NAME="$2"; shift 2 ;;
        --windows-version)
                            require_option_value "$@"; WINDOWS_VERSION="$2"
                            case "${WINDOWS_VERSION}" in
                                win10) WINDOWS_DOWNLOAD_PAGE="${WINDOWS_10_DOWNLOAD_PAGE}" ;;
                                win11) WINDOWS_DOWNLOAD_PAGE="${WINDOWS_11_DOWNLOAD_PAGE}" ;;
                            esac
                            shift 2 ;;
        --memory)           require_option_value "$@"; MEMORY_MIB="$2"; shift 2 ;;
        --vcpus)            require_option_value "$@"; VCPUS="$2"; shift 2 ;;
        --disk-size)        require_option_value "$@"; DISK_SIZE_GIB="$2"; shift 2 ;;
        --images-dir)       require_option_value "$@"; IMAGES_DIR="$2"; shift 2 ;;
        --axis-installer)   require_option_value "$@"; AXIS_INSTALLER="$2"; shift 2 ;;
        --axis-installer-url)
                            require_option_value "$@"; AXIS_INSTALLER_URL="$2"; shift 2 ;;
        --download-axis-studio-3)
                            DOWNLOAD_AXIS_STUDIO_3=1; shift ;;
        --media-cache)      require_option_value "$@"; MEDIA_CACHE_DIR="$2"; shift 2 ;;
        --download-only)    DOWNLOAD_ONLY=1; shift ;;
        --skip-axis-media)  AXIS_MEDIA=0; shift ;;
        --skip-packages)    SKIP_PACKAGES=1; shift ;;
        --dry-run)          DRY_RUN=1; shift ;;
        -h|--help)          usage; exit 0 ;;
        *)                  usage >&2; die "Unknown argument: $1" ;;
    esac
done

case "${WINDOWS_VERSION}" in
    win10|win11) ;;
    *) die "--windows-version must be win10 or win11" ;;
esac
[[ "${VM_NAME}" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] \
    || die "--name must start with a letter or number and contain only letters, numbers, dots, underscores, or hyphens"

[ -z "${WINDOWS_ISO}" ] || [ -z "${WINDOWS_ISO_URL}" ] \
    || die "--windows-iso and --windows-iso-url are mutually exclusive"
[ -z "${AXIS_INSTALLER}" ] || [ -z "${AXIS_INSTALLER_URL}" ] \
    || die "--axis-installer and --axis-installer-url are mutually exclusive"
if [ "${DOWNLOAD_AXIS_STUDIO_3}" -eq 1 ]; then
    [ -z "${AXIS_INSTALLER}" ] && [ -z "${AXIS_INSTALLER_URL}" ] \
        || die "--download-axis-studio-3 cannot be combined with another Axis installer source"
    AXIS_INSTALLER_URL="${DEFAULT_AXIS_STUDIO_3_URL}"
fi

case "${MEDIA_CACHE_DIR}" in
    /*) ;;
    *) die "--media-cache must be an absolute path" ;;
esac
[ "${MEDIA_CACHE_DIR}" != "/" ] || die "refusing to use / as the media cache"

if [ -n "${WINDOWS_ISO_URL}" ]; then
    require_https_url --windows-iso-url "${WINDOWS_ISO_URL}"
    require_microsoft_iso_url "${WINDOWS_ISO_URL}"
    # Microsoft's expiring authorization query changes while the ISO path and
    # content stay the same, so it is deliberately excluded from this key.
    WINDOWS_MEDIA_KEY="$(media_url_cache_key "${WINDOWS_ISO_URL}" strip)"
    WINDOWS_ISO="${MEDIA_CACHE_DIR}/windows-${WINDOWS_VERSION}-x86_64-${WINDOWS_MEDIA_KEY}.iso"
fi
if [ -z "${WINDOWS_ISO}" ]; then
    if [ "${DOWNLOAD_ONLY}" -ne 1 ] || [ -z "${AXIS_INSTALLER_URL}" ]; then
        die "no Windows ISO was supplied; example filenames are not bundled. Download the x64 ISO from ${WINDOWS_DOWNLOAD_PAGE}, then pass its actual path with --windows-iso, or pass Microsoft's fresh 24-hour direct link with --windows-iso-url"
    fi
fi
if [ -n "${WINDOWS_ISO}" ] && [ -z "${WINDOWS_ISO_URL}" ] && [ "${DRY_RUN}" -eq 0 ]; then
    [ -r "${WINDOWS_ISO}" ] \
        || die "Windows ISO not readable: ${WINDOWS_ISO}. Example filenames are not bundled; download it from ${WINDOWS_DOWNLOAD_PAGE} and pass the actual downloaded path"
fi

if [ -n "${AXIS_INSTALLER_URL}" ]; then
    require_https_url --axis-installer-url "${AXIS_INSTALLER_URL}"
    AXIS_INSTALLER_KIND="$(axis_installer_extension "${AXIS_INSTALLER_URL}")"
    # Generic Axis links may select the edition in their query string. Keep it
    # in the key so Online and Dongle installers can never share a cache entry.
    AXIS_MEDIA_KEY="$(media_url_cache_key "${AXIS_INSTALLER_URL}" include)"
    AXIS_INSTALLER="${MEDIA_CACHE_DIR}/AxisStudioSetup-${AXIS_MEDIA_KEY}.${AXIS_INSTALLER_KIND}"
fi
if [ -n "${AXIS_INSTALLER}" ]; then
    [ "${AXIS_MEDIA}" -eq 1 ] \
        || die "an Axis installer source cannot be used with --skip-axis-media"
    case "${AXIS_INSTALLER}" in
        *.[eE][xX][eE]) [ -n "${AXIS_INSTALLER_KIND}" ] || AXIS_INSTALLER_KIND=exe ;;
        *.[mM][sS][iI]) [ -n "${AXIS_INSTALLER_KIND}" ] || AXIS_INSTALLER_KIND=msi ;;
        *.[zZ][iI][pP]) [ -n "${AXIS_INSTALLER_KIND}" ] || AXIS_INSTALLER_KIND=zip ;;
        *) die "--axis-installer must point to an .exe, .msi, or .zip file" ;;
    esac
    if [ -z "${AXIS_INSTALLER_URL}" ] && [ "${DRY_RUN}" -eq 0 ]; then
        [ -r "${AXIS_INSTALLER}" ] \
            || die "Axis Studio installer not readable: ${AXIS_INSTALLER}. Use --download-axis-studio-3 only for compatible Anti-Mag hardware, omit --axis-installer for guided account setup, or visit ${NOITOM_DOWNLOAD_PAGE}"
    fi
fi

if [ "${DOWNLOAD_ONLY}" -eq 1 ]; then
    [ -n "${WINDOWS_ISO_URL}" ] || [ -n "${AXIS_INSTALLER_URL}" ] \
        || die "--download-only requires --windows-iso-url, --axis-installer-url, or --download-axis-studio-3"
    download_requested_media
    if [ "${DRY_RUN}" -eq 1 ]; then
        printf 'Dry run complete; no publisher media was downloaded.\n'
        [ -z "${WINDOWS_ISO_URL}" ] || printf 'Planned Windows cache: %s\n' "${WINDOWS_ISO}"
        [ -z "${AXIS_INSTALLER_URL}" ] || printf 'Planned Axis cache: %s\n' "${AXIS_INSTALLER}"
    else
        printf 'Publisher media is ready. Rerun without --download-only to create the VM.\n'
        [ -z "${WINDOWS_ISO_URL}" ] || printf 'Windows ISO: %s\n' "${WINDOWS_ISO}"
        [ -z "${AXIS_INSTALLER_URL}" ] || printf 'Axis installer: %s\n' "${AXIS_INSTALLER}"
    fi
    exit 0
fi

# ---------------------------------------------------------------- preflight
[ "$(uname -m)" = "x86_64" ] || die "Only x86_64 hosts are supported"

if ! grep -qE '(vmx|svm)' /proc/cpuinfo; then
    warn "CPU exposes no VT-x/AMD-V flags."
    warn "On physical stations: enable virtualization in BIOS/UEFI firmware."
    warn "On cloud instances without nested virtualization this cannot work."
    [ "${DRY_RUN}" -eq 1 ] || die "Hardware virtualization unavailable; aborting (use --dry-run to inspect)."
fi
if [ ! -e /dev/kvm ] && [ "${DRY_RUN}" -eq 0 ]; then
    die "/dev/kvm missing. Load the kvm_intel/kvm_amd module or enable firmware virtualization."
fi

command -v apt-get >/dev/null || warn "apt-get not found; install QEMU/libvirt packages manually."

# ------------------------------------------------------------ host packages
if [ "${SKIP_PACKAGES}" -eq 0 ] && command -v apt-get >/dev/null; then
    log "Installing host virtualization packages (sudo required)"
    HOST_PACKAGES=(
        qemu-system-x86 qemu-utils
        libvirt-daemon-system libvirt-clients virtinst virt-manager virt-viewer
        ovmf swtpm swtpm-tools
        curl
    )
    if [ "${AXIS_MEDIA}" -eq 1 ]; then
        HOST_PACKAGES+=(xorriso)
    fi
    run sudo apt-get update
    run sudo apt-get install -y "${HOST_PACKAGES[@]}"
fi

log "Enabling libvirtd and default NAT network"
run sudo systemctl enable --now libvirtd
run sudo usermod -aG libvirt,kvm "${USER}"
if [ "${DRY_RUN}" -eq 0 ]; then
    sudo virsh net-info default >/dev/null 2>&1 || die "libvirt 'default' network missing"
    sudo virsh net-autostart default >/dev/null
    sudo virsh net-start default >/dev/null 2>&1 || true
else
    run sudo virsh net-autostart default
    run sudo virsh net-start default
fi

# ----------------------------------------------------------- target checks
DISK_PATH="${IMAGES_DIR}/${VM_NAME}.qcow2"
WINDOWS_VM_ISO="${IMAGES_DIR}/${VM_NAME}-windows-installer.iso"
AXIS_SETUP_ISO="${IMAGES_DIR}/${VM_NAME}-axis-setup.iso"
if [ "${DRY_RUN}" -eq 0 ] && sudo virsh dominfo "${VM_NAME}" >/dev/null 2>&1; then
    die "Domain '${VM_NAME}' already exists. Remove it first: sudo virsh undefine ${VM_NAME} --nvram --tpm"
fi
if [ "${DRY_RUN}" -eq 0 ] && sudo test -e "${DISK_PATH}"; then
    die "Disk already exists: ${DISK_PATH} (remove it or pass --name)"
fi
if [ "${DRY_RUN}" -eq 0 ] && sudo test -e "${WINDOWS_VM_ISO}"; then
    die "Staged Windows ISO already exists: ${WINDOWS_VM_ISO} (remove it or pass --name)"
fi
if [ "${AXIS_MEDIA}" -eq 1 ] && [ "${DRY_RUN}" -eq 0 ] && sudo test -e "${AXIS_SETUP_ISO}"; then
    die "Axis setup ISO already exists: ${AXIS_SETUP_ISO} (remove it or pass --name)"
fi

# ------------------------------------------------------ publisher media
download_requested_media

# ------------------------------------------------------- virtio-win drivers
VIRTIO_ISO="${IMAGES_DIR}/virtio-win.iso"
ensure_virtio_iso

if [ "${AXIS_MEDIA}" -eq 1 ]; then
    build_axis_setup_media
fi

log "Creating sparse ${DISK_SIZE_GIB} GiB guest disk at ${DISK_PATH}"
if [ "${DRY_RUN}" -eq 1 ]; then
    DISK_PATH_TEMP="${DISK_PATH}.incoming.$$"
    run sudo qemu-img create -f qcow2 "${DISK_PATH_TEMP}" "${DISK_SIZE_GIB}G"
    run sudo ln "${DISK_PATH_TEMP}" "${DISK_PATH}"
    run sudo rm -f "${DISK_PATH_TEMP}"
    DISK_PATH_TEMP=""
else
    DISK_PATH_TEMP="$(sudo mktemp "${IMAGES_DIR}/.${VM_NAME}.qcow2.incoming.XXXXXX")"
    sudo qemu-img create -f qcow2 "${DISK_PATH_TEMP}" "${DISK_SIZE_GIB}G"
    sudo chmod 0644 "${DISK_PATH_TEMP}"
    if ! sudo ln -- "${DISK_PATH_TEMP}" "${DISK_PATH}"; then
        die "guest disk appeared while provisioning: ${DISK_PATH}"
    fi
    DISK_CREATED=1
    sudo rm -f -- "${DISK_PATH_TEMP}"
    DISK_PATH_TEMP=""
fi

# ------------------------------------------------------------- virt-install
# Windows 11 requires UEFI Secure Boot + TPM 2.0; emulate both with
# OVMF + swtpm. Windows 10 gets the same UEFI stack for consistency.
# The explicit qemu-xhci controller is required so attach-usb.sh can pass the
# Noitom transceiver (a USB/RNDIS network device) into the guest later.
OS_VARIANT="${WINDOWS_VERSION}"
if [ "${DRY_RUN}" -eq 0 ] && command -v osinfo-query >/dev/null; then
    if ! osinfo-query os short-id="${OS_VARIANT}" 2>/dev/null | grep -q "${OS_VARIANT}"; then
        warn "osinfo-db does not know '${OS_VARIANT}'; falling back to win10"
        OS_VARIANT="win10"
    fi
fi

VIRT_INSTALL_ARGS=(
    --name "${VM_NAME}"
    --memory "${MEMORY_MIB}"
    --vcpus "${VCPUS}"
    --cpu host-passthrough
    --os-variant "${OS_VARIANT}"
    --disk "path=${DISK_PATH},bus=virtio,format=qcow2"
    --cdrom "${WINDOWS_VM_ISO}"
    --disk "path=${VIRTIO_ISO},device=cdrom"
    --network network=default,model=virtio
    --controller usb,model=qemu-xhci
    --graphics spice
    --video qxl
    --boot uefi
    --noautoconsole
)
if [ "${AXIS_MEDIA}" -eq 1 ]; then
    VIRT_INSTALL_ARGS+=(
        --disk "path=${AXIS_SETUP_ISO},device=cdrom,readonly=on"
    )
fi
if [ "${WINDOWS_VERSION}" = "win11" ]; then
    VIRT_INSTALL_ARGS+=(
        --tpm backend.type=emulator,backend.version=2.0,model=tpm-crb
        --features smm.state=on
    )
fi

log "Staging the Windows installer where system libvirt can read it"
if [ "${DRY_RUN}" -eq 1 ]; then
    WINDOWS_VM_ISO_TEMP="${WINDOWS_VM_ISO}.incoming.$$"
    run sudo mkdir -p "${IMAGES_DIR}"
    run sudo install -m 0644 "${WINDOWS_ISO}" "${WINDOWS_VM_ISO_TEMP}"
    run sudo ln "${WINDOWS_VM_ISO_TEMP}" "${WINDOWS_VM_ISO}"
    run sudo rm -f "${WINDOWS_VM_ISO_TEMP}"
    WINDOWS_VM_ISO_TEMP=""
else
    sudo mkdir -p "${IMAGES_DIR}"
    WINDOWS_VM_ISO_TEMP="$(sudo mktemp "${IMAGES_DIR}/.${VM_NAME}-windows-installer.iso.incoming.XXXXXX")"
    sudo install -m 0644 "${WINDOWS_ISO}" "${WINDOWS_VM_ISO_TEMP}"
    if ! sudo ln -- "${WINDOWS_VM_ISO_TEMP}" "${WINDOWS_VM_ISO}"; then
        die "staged Windows ISO appeared while provisioning: ${WINDOWS_VM_ISO}"
    fi
    STAGED_WINDOWS_ISO_CREATED=1
    sudo rm -f -- "${WINDOWS_VM_ISO_TEMP}"
    WINDOWS_VM_ISO_TEMP=""
fi

log "Defining and starting the VM (Windows installer boots next)"
run sudo virt-install "${VIRT_INSTALL_ARGS[@]}"

# ------------------------------------------------------------- station note
run mkdir -p "${CONFIG_DIR}"
if [ "${DRY_RUN}" -eq 0 ]; then
    printf 'VM_NAME=%s\n' "${VM_NAME}" > "${CONFIG_DIR}/config.env"
fi

cat <<EOF

$(log "VM '${VM_NAME}' created.")

Next steps (details in vm/README.md):
  1. Open the console and complete Windows setup:
       virt-viewer --connect qemu:///system ${VM_NAME}
     During install, load the disk driver from the virtio-win CD
     (amd64\\${WINDOWS_VERSION}), and afterwards run virtio-win-gt-x64.msi
     from the same CD for the network/guest drivers.
EOF

if [ "${AXIS_MEDIA}" -eq 1 ]; then
    cat <<EOF
  2. In Windows, open the AXIS_SETUP CD and double-click
     START-AXIS-SETUP.cmd. The guide installs the supplied package or opens
     Noitom's official download and account pages, then explains Product-ID
     registration and Axis Studio login. Credentials are never stored here.
EOF
else
    cat <<EOF
  2. In Windows, download the correct Axis Studio edition from your Noitom
     account, install it, register the Product ID, and sign in.
EOF
fi

cat <<EOF
  3. Detect and attach the Noitom transceiver from this vm directory:
       ./attach-usb.sh detect && ./attach-usb.sh attach
  4. Configure the transceiver's RNDIS adapter in Windows as 192.168.1.100/24
     and point Axis Studio's BVH broadcast at this host: 192.168.122.1:7012 (UDP).
  5. Verify frames on the host:
       python3 vm/bridge/bvh_to_gr00t.py --probe

If this shell was not already in the 'libvirt' group, log out/in once before
running virsh without sudo.
EOF
